"$schema" = 'https://starship.rs/config-schema.json'

# --- THEME: Professional Cool Blue ---
# Flow: Dark Grey -> Blue -> Dark Grey -> Very Dark -> Lavender

format = """
[](surface0)\
$os\
$username\
[](bg:blue fg:surface0)\
$directory\
[](fg:blue bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:mantle)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:mantle bg:lavender)\
$docker_context\
$time\
[ ](fg:lavender)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Arch = "󰣇"
Ubuntu = "󰕈"
Macos = ""
Linux = "󰌽"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol $branch ](fg:text bg:surface1)]($style)'

[git_status]
style = "bg:surface1"
format = '[[($all_status$ahead_behind )](fg:text bg:surface1)]($style)'



[nodejs]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:green bg:mantle)]($style)'

[c]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:blue bg:mantle)]($style)'

[rust]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:red bg:mantle)]($style)'

[golang]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:blue bg:mantle)]($style)'

[php]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:blue bg:mantle)]($style)'

[java]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:red bg:mantle)]($style)'

[kotlin]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:blue bg:mantle)]($style)'

[haskell]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:purple bg:mantle)]($style)'

[python]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:yellow bg:mantle)]($style)'

[docker_context]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $context) ](fg:mantle bg:lavender)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:mantle bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:blue)'
error_symbol = '[✗](bold fg:red)'
