format = """
[](surface0)\
$os\
$username\
[](bg:blue fg:surface0)\
$directory\
[](fg:blue bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:mantle)\
$docker_context\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#cdd6f4"
flamingo = "#bac2de"
pink = "#bac2de"
orange = "#bac2de"
red = "#a6adc8"
maroon = "#a6adc8"
peach = "#bac2de"
yellow = "#cdd6f4"
green = "#cdd6f4"
teal = "#bac2de"
sky = "#bac2de"
sapphire = "#a6adc8"
blue = "#9399b2"
lavender = "#7f849c"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol $branch ](fg:text bg:surface1)]($style)'

[git_status]
style = "bg:surface1"
format = '[[($all_status$ahead_behind )](fg:text bg:surface1)]($style)'


[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:blue)'
error_symbol = '[✗](bold fg:red)'
